version: '2'
services:
    #ror:
    #    build: ror/.
    #    command: bundle exec rails s -p 80 -b '0.0.0.0'
    #    volumes:
    #        - ./ror/:/ror
    #ports:
    #    - "3000:3000"
    #    restart: always
    #networks:
    #    - nginx_default
    reactjs:
        build: reactjs/.
        command: http-server ./build/. -p 80
        depends_on: 
            - node
        #ports:
        #    - "8001:80"
        volumes:
            - ./reactjs/:/reactjs
            - /reactjs/node_modules
        #restart: always
        networks:
            - nginx_default
    node:
        build: node/.
        command: node server.js
        #depends_on: 
        # links:
        #       - ror
        #     - redis
        volumes:
            - ./node/:/node
            - /node/node_modules
        #ports:
        #    - "3000:3000"
        #restart: always
        networks:
            - nginx_default
    loopback:
        build: loopback/.
        command: node .
        #depends_on: 
        volumes:
            - ./loopback/server/:/loopback/server/
            - ./loopback/client/:/loopback/client/
            - /loopback/node_modules
        #restart: always
        #ports:
        #    - "3000:3000"
        networks:
            - nginx_default
        #ionic:
        #build: ionic/.
        #command: bash -c "npm rebuild node-sass --force && ionic serve --no-interactive --address 0.0.0.0"
        #command: http-server ./platforms/browser/www -p 80
        #command: bash -c "ionic cordova run browser --no-interactive --address 0.0.0.0 --nolivereload"
        #depends_on: 
        #    - ror
        #ports:
        #    - "8080:80"
        #volumes:
        #    - ./ionic/:/ionic
        #restart: always
        #networks:
        #    - nginx_default
        #redis:
        #build: redis/.
        #image: redis
        #ports:
        #    - "6379:6379"
        #restart: always
        #networks:
        #    - nginx_default
        #    nginx:
        #build: nginx/.
        #ports:
        #    - "8080:80"
        #volumes:
        #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #    - ./nginx/data:/nginx/data
        #    - ./nginx/logs:/nginx/logs
        #restart: always
        #depends_on:
        #        - ror
        #        - node
        #        - http
        #        - loopback
networks:
    nginx_default:
        external: true
